services:
  apache62:
    image: httpd:2.4.62
    ports:
      - "8062:80"
    volumes:
      - ./apache-html:/usr/local/apache2/htdocs/
      - ./apache-conf:/usr/local/apache2/conf/
      - ./sock:/run/sock
  apache61:
    image: httpd:2.4.61
    ports:
      - "8061:80"
    volumes:
      - ./apache-html:/usr/local/apache2/htdocs/
      - ./apache-conf:/usr/local/apache2/conf/
      - ./sock:/run/sock
  app:
    image: nginx:1.21
    volumes:
      - ./nginx-html:/usr/share/nginx/html
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sock:/run/sock
