version: "3.0"
services:
  apache48:
    image: httpd:2.4.48
    ports:
      - "8048:80"
    volumes:
      - ./apache-html:/usr/local/apache2/htdocs/
      - ./apache-conf:/usr/local/apache2/conf/
      - ./sock:/run/sock
  apache49:
    image: httpd:2.4.49
    ports:
      - "8049:80"
    volumes:
      - ./apache-html:/usr/local/apache2/htdocs/
      - ./apache-conf:/usr/local/apache2/conf/
      - ./sock:/run/sock
  app:
    image: nginx:1.21
    volumes:
      - ./nginx-html:/usr/share/nginx/html
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sock:/run/sock
